apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: lucaiacono2275
    repository: jx3-kubernetes-vault-4
  - key: staging
  - key: production
  ingress:
    domain: ihsws.it
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: luca.iacono@gmail.com
      enabled: true
      production: false
  pipelineUser:
    username: lucaiacono2275
  repository: bucketrepo
  secretStorage: vault
  vault: {}
  webhook: lighthouse
