apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: luca.iacono@gmail.com  
    privateKeySecretRef:
      name: letsencrypt-dns01-staging
    solvers:
    - dns01:
        cloudDNS:
          # The ID of the GCP project
          project: ihsws-335710
          # This is the secret used to access the service account
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json