# Source: addons/templates/secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: clouddns-dns01-solver-svc-acct
  namespace: cert-manager
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: key.json
      key: secret/data/clouddns/dns01/solver/svc/acct
      property: key.json
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'addons-cert-manager'
    type: Opaque
