# Source: cert-manager/templates/startupapicheck-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: cert-manager-startupapicheck
  namespace: "cert-manager"
  labels:
    app: startupapicheck
    app.kubernetes.io/name: startupapicheck
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/component: "startupapicheck"
    app.kubernetes.io/version: "v1.8.0"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: cert-manager-v1.8.0
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "1"
    meta.helm.sh/release-name: 'cert-manager'
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: startupapicheck
        app.kubernetes.io/name: startupapicheck
        app.kubernetes.io/instance: cert-manager
        app.kubernetes.io/component: "startupapicheck"
        app.kubernetes.io/version: "v1.8.0"
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: cert-manager-v1.8.0
    spec:
      restartPolicy: OnFailure
      serviceAccountName: cert-manager-startupapicheck
      securityContext:
        runAsNonRoot: true
      containers:
        - name: cert-manager
          image: "quay.io/jetstack/cert-manager-ctl:v1.8.0"
          imagePullPolicy: IfNotPresent
          args:
            - check
            - api
            - --wait=1m
          securityContext:
            allowPrivilegeEscalation: false
