# Source: reflector/templates/rbac-clusterRole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reflector
  labels:
    app.kubernetes.io/name: reflector
    helm.sh/chart: reflector-4.1.12
    app.kubernetes.io/instance: reflector
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'cluster'
  annotations:
    meta.helm.sh/release-name: 'reflector'
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["*"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["*"]
  - apiGroups: ["certmanager.k8s.io"]
    resources: ["certificates", "certificates/finalizers"]
    verbs: ["*"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates", "certificates/finalizers"]
    verbs: ["*"]
