# Source: reflector/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reflector
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: reflector
    helm.sh/chart: reflector-4.1.12
    app.kubernetes.io/instance: reflector
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'reflector'
    wave.pusher.com/update-on-config-change: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reflector
      app.kubernetes.io/instance: reflector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reflector
        app.kubernetes.io/instance: reflector
    spec:
      containers:
        - name: reflector
          image: "emberstack/kubernetes-reflector:release-4.1.12"
          imagePullPolicy: IfNotPresent
          env:
            - name: ES_Reflector__Extensions__CertManager__Enabled
              value: "true"
            - name: ES_Serilog__MinimumLevel__Default
              value: "Information"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {}
      serviceAccountName: reflector
